
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create




---
spring:

  profiles: development

---
spring:

  profiles: production